// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251027212348_AdicionarSeedData")]
    partial class AdicionarSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("api.Models.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Empresa")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CriadoEm = new DateTime(2024, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "joao.silva@email.com",
                            Empresa = "Tech Solutions Ltda",
                            Nome = "João Silva",
                            Telefone = "(11) 98765-4321"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CriadoEm = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "maria.santos@email.com",
                            Empresa = "Inovação Digital SA",
                            Nome = "Maria Santos",
                            Telefone = "(21) 97654-3210"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CriadoEm = new DateTime(2024, 10, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "pedro.oliveira@email.com",
                            Empresa = "Consultoria Empresarial",
                            Nome = "Pedro Oliveira",
                            Telefone = "(31) 96543-2109"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CriadoEm = new DateTime(2024, 10, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ana.costa@email.com",
                            Empresa = "StartUp Ventures",
                            Nome = "Ana Costa",
                            Telefone = "(41) 95432-1098"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CriadoEm = new DateTime(2024, 10, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "carlos.mendes@email.com",
                            Empresa = "Global Trading Corp",
                            Nome = "Carlos Mendes",
                            Telefone = "(51) 94321-0987"
                        });
                });

            modelBuilder.Entity("api.Models.Oportunidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataFechamentoPrevista")
                        .HasColumnType("date");

                    b.Property<string>("Estagio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<int>("Probabilidade")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Oportunidades");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            ClienteId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CriadoEm = new DateTime(2024, 10, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataFechamentoPrevista = new DateOnly(2025, 11, 26),
                            Estagio = "Negociacao",
                            Ordem = 1,
                            Probabilidade = 80,
                            Titulo = "Implementação de Sistema ERP",
                            Valor = 150000m
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111112"),
                            ClienteId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CriadoEm = new DateTime(2024, 10, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataFechamentoPrevista = new DateOnly(2025, 12, 11),
                            Estagio = "Proposta",
                            Ordem = 2,
                            Probabilidade = 60,
                            Titulo = "Consultoria de TI",
                            Valor = 50000m
                        },
                        new
                        {
                            Id = new Guid("a2222222-2222-2222-2222-222222222221"),
                            ClienteId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CriadoEm = new DateTime(2024, 10, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataFechamentoPrevista = new DateOnly(2025, 12, 26),
                            Estagio = "Qualificacao",
                            Ordem = 1,
                            Probabilidade = 70,
                            Titulo = "Desenvolvimento de App Mobile",
                            Valor = 200000m
                        },
                        new
                        {
                            Id = new Guid("a2222222-2222-2222-2222-222222222222"),
                            ClienteId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CriadoEm = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataFechamentoPrevista = new DateOnly(2025, 10, 22),
                            Estagio = "FechadoGanho",
                            Ordem = 2,
                            Probabilidade = 90,
                            Titulo = "Suporte Técnico Anual",
                            Valor = 30000m
                        },
                        new
                        {
                            Id = new Guid("a3333333-3333-3333-3333-333333333331"),
                            ClienteId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CriadoEm = new DateTime(2024, 10, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataFechamentoPrevista = new DateOnly(2026, 1, 25),
                            Estagio = "Prospeccao",
                            Ordem = 1,
                            Probabilidade = 50,
                            Titulo = "Migração para Cloud",
                            Valor = 100000m
                        },
                        new
                        {
                            Id = new Guid("a3333333-3333-3333-3333-333333333332"),
                            ClienteId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CriadoEm = new DateTime(2024, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataFechamentoPrevista = new DateOnly(2025, 12, 16),
                            Estagio = "Qualificacao",
                            Ordem = 2,
                            Probabilidade = 40,
                            Titulo = "Treinamento em Segurança",
                            Valor = 25000m
                        },
                        new
                        {
                            Id = new Guid("a4444444-4444-4444-4444-444444444441"),
                            ClienteId = new Guid("44444444-4444-4444-4444-444444444444"),
                            CriadoEm = new DateTime(2024, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataFechamentoPrevista = new DateOnly(2025, 11, 21),
                            Estagio = "Proposta",
                            Ordem = 1,
                            Probabilidade = 85,
                            Titulo = "Website Corporativo",
                            Valor = 45000m
                        },
                        new
                        {
                            Id = new Guid("a4444444-4444-4444-4444-444444444442"),
                            ClienteId = new Guid("44444444-4444-4444-4444-444444444444"),
                            CriadoEm = new DateTime(2024, 10, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataFechamentoPrevista = new DateOnly(2025, 10, 17),
                            Estagio = "FechadoPerdido",
                            Ordem = 2,
                            Probabilidade = 20,
                            Titulo = "Integração de APIs",
                            Valor = 35000m
                        },
                        new
                        {
                            Id = new Guid("a5555555-5555-5555-5555-555555555551"),
                            ClienteId = new Guid("55555555-5555-5555-5555-555555555555"),
                            CriadoEm = new DateTime(2024, 10, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataFechamentoPrevista = new DateOnly(2025, 12, 6),
                            Estagio = "Negociacao",
                            Ordem = 1,
                            Probabilidade = 65,
                            Titulo = "Sistema de BI",
                            Valor = 180000m
                        },
                        new
                        {
                            Id = new Guid("a5555555-5555-5555-5555-555555555552"),
                            ClienteId = new Guid("55555555-5555-5555-5555-555555555555"),
                            CriadoEm = new DateTime(2024, 10, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataFechamentoPrevista = new DateOnly(2025, 11, 16),
                            Estagio = "Proposta",
                            Ordem = 2,
                            Probabilidade = 75,
                            Titulo = "Licenças de Software",
                            Valor = 20000m
                        });
                });

            modelBuilder.Entity("api.Models.Oportunidade", b =>
                {
                    b.HasOne("api.Models.Cliente", "Cliente")
                        .WithMany("Oportunidades")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("api.Models.Cliente", b =>
                {
                    b.Navigation("Oportunidades");
                });
#pragma warning restore 612, 618
        }
    }
}
